
###############
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor=,preferred,auto,auto

# Instead, just describe it normally:
#monitor = eDP-1, 3456x2160@120, auto, 1
#monitor = HDMI-A-1, 2560x1440@59.95, auto, 1   # or HDMI‑A‑1, depend on your output
